### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by CarroCremello** [CarroForslund/fsjs-project6#1]
- [x] Running npm install installs relevant dependencies (Have to check this)
- [x] Write to CSV file only once
- [x] Make sure the timestamp is correctly formatted for the error log

**Comment by CarroCremello** [comment]
Everything is ready for submission. :)
